// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATbrArlnoJI00fYvSiQnFKza81r9VoWog',
    appId: '1:53757301789:web:0dcfe10015f36847ec22f4',
    messagingSenderId: '53757301789',
    projectId: 'test-5ab44',
    authDomain: 'test-5ab44.firebaseapp.com',
    storageBucket: 'test-5ab44.firebasestorage.app',
    measurementId: 'G-KSXCYZ09KW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiHSA0Ge8-NRij5qfle_bU-NqwkcXNA7E',
    appId: '1:53757301789:android:3b745e3b2c33eb45ec22f4',
    messagingSenderId: '53757301789',
    projectId: 'test-5ab44',
    storageBucket: 'test-5ab44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbOLmuPOd-g2zPeXDzZCdWGBxGdTOC5-M',
    appId: '1:53757301789:ios:05d218514002bdd4ec22f4',
    messagingSenderId: '53757301789',
    projectId: 'test-5ab44',
    storageBucket: 'test-5ab44.firebasestorage.app',
    iosBundleId: 'com.devproffer.projectGolf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbOLmuPOd-g2zPeXDzZCdWGBxGdTOC5-M',
    appId: '1:53757301789:ios:05d218514002bdd4ec22f4',
    messagingSenderId: '53757301789',
    projectId: 'test-5ab44',
    storageBucket: 'test-5ab44.firebasestorage.app',
    iosBundleId: 'com.devproffer.projectGolf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATbrArlnoJI00fYvSiQnFKza81r9VoWog',
    appId: '1:53757301789:web:0d06414315f0f512ec22f4',
    messagingSenderId: '53757301789',
    projectId: 'test-5ab44',
    authDomain: 'test-5ab44.firebaseapp.com',
    storageBucket: 'test-5ab44.firebasestorage.app',
    measurementId: 'G-VBNTG354WV',
  );
}
